.gitignore, Dockerfile, build.gradle, src/main/java/com/hongik/controller/HealthCheckController.java, src/main/resources/application.properties, src/main/resources/application.yml
=> [Infra] Github action을 활용하여 CI CD를 구축합니다.

.github/ISSUE_TEMPLATE/feature.md, .github/PULL_REQUEST_TEMPLATE.md
=> [Docs] issue, PR template 추가

.github/pull_request_template.md, src/main/java/com/hongik/dto/ApiResponse.java, src/main/java/com/hongik/exception/ApiControllerAdvice.java, src/main/java/com/hongik/exception/AppException.java, src/main/java/com/hongik/exception/ErrorCode.java
close #8 
- ApiResponse 구현
- ApiControllerAdvice, ErrorCode 구현
- PR 템플릿 추가
=> [Feature] 공통 응답, 예외 컨트롤러 구현

src/main/java/com/hongik/config/SecurityLoginSwagger.java, src/main/java/com/hongik/controller/user/UserController.java
close #12 
- Security 로그인 Swagger 적용
- API 상세 설명 작성
=> [Docs] Security Login - Swagger 적용, Swagger를 활용하여 API 상세 설명 작성

src/main/java/com/hongik/controller/study/StudySessionController.java, src/main/java/com/hongik/controller/user/UserController.java, src/main/java/com/hongik/domain/study/StudySession.java, src/main/java/com/hongik/domain/study/StudySessionRepository.java, src/main/java/com/hongik/dto/study/request/StudySessionCreateRequest.java, src/main/java/com/hongik/dto/study/response/StudySessionResponse.java, src/main/java/com/hongik/exception/ErrorCode.java, src/main/java/com/hongik/service/study/StudySessionService.java, src/main/java/com/hongik/service/user/CustomUserDetailsService.java, src/main/java/com/hongik/service/user/UserService.java, src/test/java/com/hongik/controller/study/StudySessionControllerTest.java, src/test/java/com/hongik/controller/user/UserControllerTest.java, src/test/java/com/hongik/service/study/StudySessionServiceTest.java, src/test/java/com/hongik/service/user/UserServiceTest.java
close #14 
- Entity 설계
- 열람실 이용 종료 기능 구현
=> [Feature] StudySession Entity 설계 및 열람실 이용 종료 기능 구현

src/main/java/com/hongik/controller/study/StudySessionController.java, src/main/java/com/hongik/domain/study/StudySessionRepository.java, src/main/java/com/hongik/dto/study/response/StudyCountResponse.java, src/main/java/com/hongik/dto/study/response/StudyDurationResponse.java, src/main/java/com/hongik/service/study/StudySessionService.java, src/test/java/com/hongik/controller/study/StudySessionControllerTest.java, src/test/java/com/hongik/domain/study/StudySessionRepositoryTest.java, src/test/java/com/hongik/service/study/StudySessionServiceTest.java, src/test/resources/application.yml
close #16 
- 입력한 날짜 시간, StudyCount 조회 기능 구현
- 모든 날짜 StudyCount 조회 기능 구현
=> [Feature] 입력한 날짜에 맞게 투데이 및 월간 시간, StudyCount 불러오는 기능 구현

src/main/java/com/hongik/config/SecurityLoginSwagger.java, src/main/java/com/hongik/config/SwaggerConfig.java, src/main/java/com/hongik/controller/study/StudySessionController.java, src/main/java/com/hongik/controller/user/UserController.java, src/main/java/com/hongik/dto/study/response/StudyCountResponse.java, src/main/java/com/hongik/dto/study/response/StudyDurationResponse.java
close #18 
- 구현한 기능 API 명세서 작성
=> [Docs] Study, User - Swagger 문서 작업

.github/workflows/cicd.yml, .gitignore, build.gradle, src/main/java/com/hongik/config/SecurityConfig.java, src/main/java/com/hongik/domain/user/User.java, src/main/java/com/hongik/dto/user/response/CustomOAuth2User.java, src/main/java/com/hongik/dto/user/response/GoogleResponse.java, src/main/java/com/hongik/dto/user/response/OAuth2Response.java, src/main/java/com/hongik/service/user/CustomOAuth2UserService.java, src/main/java/com/hongik/service/user/CustomSuccessHandler.java, src/main/resources/application.yml, src/test/resources/application-test.yml, src/test/resources/application.yml
=>  [Feature] Google 소셜 로그인 1차 기능만 구현

src/main/java/com/hongik/controller/wisesaying/WiseSayingController.java, src/main/java/com/hongik/domain/wisesaying/WiseSaying.java, src/main/java/com/hongik/domain/wisesaying/WiseSayingRepository.java, src/main/java/com/hongik/dto/wisesaying/request/WiseSayingCreateRequest.java, src/main/java/com/hongik/dto/wisesaying/response/WiseSayingResponse.java, src/main/java/com/hongik/service/wisesaying/WiseSayingService.java, src/test/java/com/hongik/controller/wisesaying/WiseSayingControllerTest.java, src/test/java/com/hongik/service/wisesaying/WiseSayingServiceTest.java
close #24 
- 명언 JSON으로 저장 기능 구현
- 명언 현재 날짜 기준으로 조회 기능 구현
=> [Feature] 명언 생성 및 조회 기능 구현

src/main/java/com/hongik/controller/study/StudySessionController.java, src/main/java/com/hongik/domain/study/StudySessionRepository.java, src/main/java/com/hongik/service/study/StudySessionService.java, src/test/java/com/hongik/controller/study/StudySessionControllerTest.java, src/test/java/com/hongik/service/study/StudySessionServiceTest.java
close #26 
- 현재 날짜 기준 일주일 날짜, 공부 횟수 조회 기능 구현
=> [Feature] 현재 날짜 기준 주단위 날짜 및 요일, 날짜에 대한 공부 횟수 조회

src/main/java/com/hongik/controller/study/StudySessionController.java, src/main/java/com/hongik/domain/study/StudySessionRepository.java, src/main/java/com/hongik/dto/study/response/StudyDurationResponse.java, src/main/java/com/hongik/service/study/StudySessionService.java, src/test/java/com/hongik/controller/study/StudySessionControllerTest.java, src/test/java/com/hongik/service/study/StudySessionServiceTest.java
close #28 
- 연간, 월간, 투데이, 학기 공부 시간 측정 기능 구현
- 각각 DB조회로 4번 조회하여 데이터 합쳐서 제공
=> [Feature] 연간, 학기, 월간, 투데이 공부 시간 측정 기능 구현

src/main/java/com/hongik/controller/study/StudySessionController.java, src/main/java/com/hongik/domain/study/StudySessionRepository.java, src/main/java/com/hongik/dto/study/response/RankResponse.java, src/main/java/com/hongik/dto/study/response/StudyRankingResponse.java, src/main/java/com/hongik/service/study/StudySessionService.java, src/test/java/com/hongik/controller/study/StudySessionControllerTest.java
=> [Feature] (임시) 학과별 주차 랭킹 기능  year, month, day값 받아서 조회 기능 구현

src/main/java/com/hongik/config/SecurityConfig.java, src/main/java/com/hongik/controller/weekly/WeeklyController.java, src/main/java/com/hongik/domain/weekly/Weekly.java, src/main/java/com/hongik/domain/weekly/WeeklyRepository.java, src/main/java/com/hongik/dto/weekly/response/WeeklyResponse.java, src/main/java/com/hongik/exception/ErrorCode.java, src/main/java/com/hongik/jwt/JwtUtil.java, src/main/java/com/hongik/service/weekly/WeeklyService.java, src/test/java/com/hongik/controller/weekly/WeeklyControllerTest.java, src/test/java/com/hongik/service/weekly/WeeklyServiceTest.java
- 연도에 대한 주차 데이터 생성 기능 구현
- 서버 기준 20xx에 대한 주차 데이터 조회 기능 구현
=> [Feature] 주차 테이블 생성 및 조회 기능 구현

src/main/java/com/hongik/controller/auth/AuthController.java, src/main/java/com/hongik/controller/study/StudySessionController.java, src/main/java/com/hongik/controller/user/UserController.java, src/main/java/com/hongik/dto/auth/request/LoginRequest.java, src/main/java/com/hongik/service/auth/GoogleLoginService.java, src/main/java/com/hongik/service/auth/apple/AppleSocialLoginService.java, src/main/java/com/hongik/service/study/StudySessionService.java, src/test/java/com/hongik/controller/study/StudySessionControllerTest.java, src/test/java/com/hongik/controller/user/UserControllerTest.java, src/test/java/com/hongik/service/study/StudySessionServiceTest.java
close #36 
- year, month, day로 랭킹을 구하는 방식에서
- yearWeek를 바로 넘겨서 랭킹을 구하는 방식으로 수정
=> [Feature] 랭킹 기능 파라미터값 변경

src/main/java/com/hongik/controller/study/StudySessionController.java, src/main/java/com/hongik/controller/wisesaying/WiseSayingController.java, src/test/java/com/hongik/controller/study/StudySessionControllerTest.java, src/test/java/com/hongik/controller/wisesaying/WiseSayingControllerTest.java
close #38 
- ApiResponse 공통 응답에서
- ResponseEntity로 전부 변경했습니다.
=> [Refactor] API 응답 ApiResponse -> ResponseEntity로 변경

src/main/java/com/hongik/controller/library/LibraryController.java, src/main/java/com/hongik/domain/library/Library.java, src/main/java/com/hongik/domain/library/LibraryRepository.java, src/main/java/com/hongik/dto/library/response/LibraryResponse.java, src/main/java/com/hongik/exception/ErrorCode.java, src/main/java/com/hongik/service/library/LibraryService.java, src/test/java/com/hongik/controller/library/LibraryControllerTest.java, src/test/java/com/hongik/service/library/LibraryServiceTest.java
close #40 
- 열람실 좌석 이용 시간 조회 기능 구현
- 열람실 좌석 이용 시간 수정 기능 구현
=> [Feature] 도서관 이용 시간(4시간, 6시간) 조회, 수정 기능 구현

src/main/java/com/hongik/config/SecurityConfig.java, src/main/java/com/hongik/exception/TokenErrorResponse.java, src/main/java/com/hongik/jwt/CustomAccessDeniedHandler.java, src/main/java/com/hongik/jwt/CustomJwtAuthenticationEntryPoint.java, src/main/java/com/hongik/jwt/JwtFilter.java, src/main/java/com/hongik/jwt/JwtUtil.java
close #42 
- 403 권한 예외 추가
- 401 토큰 관련 예외 추가
- 메세지는 토큰 유효기간 만료만 추가되어있음.
=> [Feature] 토큰 만료 예외 응답 추가 및 에러코드 작성

.github/workflows/cicd.yml, .gitignore, build.gradle, src/main/java/com/hongik/HongikApplication.java, src/main/java/com/hongik/migration/firebase/FirebaseConfig.java, src/main/java/com/hongik/migration/firebase/FirebaseController.java, src/main/java/com/hongik/migration/firebase/FirebaseService.java, src/main/java/com/hongik/migration/firebase/Member.java, src/main/java/com/hongik/migration/firebase/StudyDay.java
close #50 
- 마이그레이션 바로할 수 있게 세팅
=> [Feature] 파이어베이스 -> 서버 DB 마이그레이션 세팅

src/main/java/com/hongik/controller/library/LibraryController.java, src/main/java/com/hongik/controller/study/StudySessionController.java, src/main/java/com/hongik/controller/user/UserController.java, src/main/java/com/hongik/controller/weekly/WeeklyController.java, src/main/java/com/hongik/controller/wisesaying/WiseSayingController.java
close #52 
- API 응답값 ResponseEntity 에서
- ApiResponse로 전부 변경했습니다.
=> [Refactor] 응답 형식 ResponseEntity -> ApiResponse

src/main/java/com/hongik/config/SecurityConfig.java
- /login 권한 
- /login-google 권한 permitAll로 변경
=> [Refactor] 구글 소셜 로그인 url Security 권한 permitAll 설정

src/main/java/com/hongik/config/SecurityConfig.java, src/main/java/com/hongik/config/SwaggerConfig.java, src/main/java/com/hongik/controller/auth/AuthController.java, src/main/java/com/hongik/controller/library/LibraryController.java, src/main/java/com/hongik/controller/study/StudySessionController.java, src/main/java/com/hongik/controller/user/UserController.java, src/main/java/com/hongik/controller/weekly/WeeklyController.java, src/main/java/com/hongik/controller/wisesaying/WiseSayingController.java, src/main/java/com/hongik/exception/ErrorCode.java, src/main/java/com/hongik/exception/TokenErrorResponse.java, src/main/java/com/hongik/jwt/CustomAccessDeniedHandler.java, src/main/java/com/hongik/jwt/CustomJwtAuthenticationEntryPoint.java, src/main/java/com/hongik/swagger/ApiErrorCodeExample.java, src/main/java/com/hongik/swagger/ApiErrorCodeExamples.java, src/main/java/com/hongik/swagger/ErrorResponseDto.java, src/main/java/com/hongik/swagger/ExampleHolder.java
close #59 
- 기존 컨트롤러 스웨거에
- 예외 추가
=> [Docs] Swagger 예외 코드 문서화

.github/workflows/cicd.yml
close #61 
- BLUE/GREEN 배포 방식에서
- 일반 배포로 변경
=> [Refactor] 무중단 배포 -> 일반 배포로 변경

src/main/java/com/hongik/controller/study/StudySessionController.java, src/main/java/com/hongik/domain/study/StudySessionRepository.java, src/main/java/com/hongik/dto/study/response/StudyDurationResponse.java, src/main/java/com/hongik/service/study/StudySessionService.java, src/test/java/com/hongik/domain/study/StudySessionRepositoryTest.java, src/test/java/com/hongik/service/study/StudySessionServiceTest.java
close #63 
- Minute 값으로 응답하던 시간을
- Hour, Minute 또는 Hour로 응답하도록 변경
=> [Feature] 기존 공부 시간 응답 MINUTE -> SECOND를 구하고 HOUR로 출력 로직 변경

src/main/java/com/hongik/controller/user/UserController.java
close #69 
- 기존 버전이 제대로 적용이 되지 않았던 것을
- 적용시키기 위해 재배포
=> [Fix] (배포) 최신 버전으로 제대로 적용되지 않은 버그 수정

src/main/java/com/hongik/config/SecurityConfig.java, src/main/java/com/hongik/controller/user/UserController.java, src/main/java/com/hongik/exception/ApiControllerAdvice.java, src/test/java/com/hongik/controller/user/UserControllerTest.java
close #71 
- RequestParam Validation, NotAllowMethod 등 
- 공통 예외 핸들러에 추가하고, 닉네임 중복 검사 테스트 코드 작성
=> [Feature] 공통 예외 ExceptionHandler 값 추가

src/main/java/com/hongik/domain/department/Department.java, src/main/java/com/hongik/domain/department/DepartmentRepository.java
close #75 
- department 테이블 생성 후, DB에서 데이터를 관리합니다.
=> [Feature] department 테이블 생성 후, 데이터 적재

src/main/java/com/hongik/controller/study/StudySessionController.java, src/main/java/com/hongik/dto/study/response/StudyCountLocalDateResponse.java, src/main/java/com/hongik/dto/study/response/StudyCountResponse.java, src/main/java/com/hongik/dto/study/response/StudyCountResponse2.java, src/main/java/com/hongik/dto/weekly/response/WeeklyOneResponse.java, src/main/java/com/hongik/service/study/StudySessionService.java, src/main/java/com/hongik/service/weekly/WeeklyService.java, src/test/java/com/hongik/controller/study/StudySessionControllerTest.java, src/test/java/com/hongik/service/study/StudySessionServiceTest.java
close #79 
- 날짜 형식 yyyy-MM-dd 에서
- M/dd 로 변경
=> [Refactor] /week API 기존 날짜 형식 yyyy-MM-dd -> M/dd 로 변경

.github/workflows/cicd.yml, .gitignore, src/main/java/com/hongik/controller/HealthCheckController.java, src/main/resources/application.yml
close #83 
- 기존 운영 서버 하나로 관리했던 것을
- 운영, 개발 서버 두 개로 나누었습니다.
=> [Infra] 개발 서버, 운영 서버 분리 스크립트 작성

src/main/java/com/hongik/config/SwaggerConfig.java, src/main/java/com/hongik/service/auth/AuthService.java
close #86 
- Swagger API 테스트 진행할 때, 토큰 넣을 수 있는 기능 구현
=> [Feature] Swagger JWT 토큰 사용할 수 있게 헤더 추가

src/main/java/com/hongik/domain/study/StudySessionRepository.java, src/main/java/com/hongik/service/auth/AuthService.java
=> [Fix] 학기 공부 시간 Null Exception 해결

src/main/java/com/hongik/service/auth/AuthService.java, src/main/java/com/hongik/service/user/UserService.java
close #101 
- 테스트를 위해 5분으로 설정해놨던 값을
- 다시 365일로 변경했습니다.
=> [Refactor] Google Login 액세스 토큰 시간 365일로 수정

src/main/java/com/hongik/domain/user/SocialPlatform.java, src/main/java/com/hongik/domain/user/User.java, src/main/java/com/hongik/service/auth/AuthService.java
close #119 
- 유저 엔티티에 소셜플랫폼 컬럼을 추가하였습니다.
=> [Feature] 회원 엔티티에 소셜플랫폼 컬럼 추가

src/main/java/com/hongik/service/user/UserService.java
- 기존 알람 메세지에 닉네임만 표시했던 것을
- 총 회원 수, 플랫폼까지 추가하였습니다.
=> [Feature] 최종 회원가입 알람 메세지에 총 회원수, 플랫폼 추가

src/main/java/com/hongik/domain/study/StudySessionRepository.java, src/test/java/com/hongik/service/study/StudySessionServiceTest.java
- 기존에는 1~32등까지 순위로 나누어졌던 랭킹 시스템을
- 동일한 공부시간이면 동일한 순위로 수정했습니다.
=> [Refactor] 학과별 공부 시간이 동일하면 동일한 랭크로 수정

src/main/java/com/hongik/controller/user/UserController.java, src/main/java/com/hongik/domain/user/User.java, src/main/java/com/hongik/dto/user/request/UserProfileRequest.java, src/main/java/com/hongik/service/user/UserService.java, src/test/java/com/hongik/controller/user/UserControllerTest.java, src/test/java/com/hongik/service/user/UserServiceTest.java
close #126 
- 프로필 (닉네임, 학과) 수정 기능을 구현했습니다.
=> [Feature] 학과, 닉네임 수정 기능 구현

src/main/java/com/hongik/controller/user/UserController.java, src/main/java/com/hongik/domain/user/User.java, src/main/java/com/hongik/dto/user/request/UserDeviceTokenRequest.java, src/main/java/com/hongik/dto/user/response/DeviceTokenResponse.java, src/main/java/com/hongik/dto/user/response/UserDeviceTokenResponse.java, src/main/java/com/hongik/service/user/UserService.java, src/test/java/com/hongik/controller/user/UserControllerTest.java, src/test/java/com/hongik/service/user/UserServiceTest.java
close #146 
- 유저 DeviceToken 추가 기능을 구현했습니다.
- DB를 조회하여 UserDeviceToken 값과 RequestDeviceToken 값이 다르면 Request 값으로 갱신합니다.
- DB를 조회하여 UserDeviceToken 값이 null인 경우, Request 값으로 갱신합니다.
- 유저 DeviceToken 조회 기능을 구현했습니다.
- DeviceToken이 존재하지 않으면 null을 반환합니다.
=> [Feature] 유저 DeviceToken 추가 및 조회 기능 구현

src/main/java/com/hongik/controller/study/StudySessionController.java, src/main/java/com/hongik/domain/library/Library.java, src/main/java/com/hongik/domain/study/StudySession.java, src/main/java/com/hongik/dto/study/request/EndStudySessionRequest.java, src/main/java/com/hongik/dto/study/response/EndStudySessionResponse.java, src/main/java/com/hongik/exception/ErrorCode.java, src/main/java/com/hongik/service/study/StudySessionService.java
=> [Feature] 열람실 이용 종료 기능 구현

src/main/java/com/hongik/controller/study/StudySessionController.java, src/main/java/com/hongik/domain/study/StudySessionRepository.java, src/main/java/com/hongik/dto/study/response/StudyingUserResponse.java, src/main/java/com/hongik/dto/study/response/UserStudyDuration.java, src/main/java/com/hongik/service/study/StudySessionService.java
=> [Feature] 열람실 이용 중인 회원 조회 기능 구현

.github/workflows/HongikYeolgong2-dev.yml, .gitignore, build.gradle, src/main/java/com/hongik/controller/auth/AppleMigrationController.java, src/main/java/com/hongik/domain/user/User.java, src/main/java/com/hongik/domain/user/UserRepository.java, src/main/java/com/hongik/dto/auth/response/AppleTransferResponse.java, src/main/java/com/hongik/dto/auth/response/AppleUserInfoResponse.java, src/main/java/com/hongik/service/auth/apple/AppleMigrationService.java, src/main/resources/application.yml
- 앱 이전하면서 변동된 애플 회원 sub값 새로운 sub값으로 교체하는 기능 구현
=> [Feature] 앱 이전 기능 구현

.github/workflows/HongikYeolgong2-dev.yml
=> chore: key-id 경로 수정

src/main/java/com/hongik/service/auth/apple/AppleMigrationService.java
=> fix: key 파일 정보 가져오기 수정

.github/workflows/HongikYeolgong2-prod.yml
=> chore: key 파일 경로 추가
